using System.Text;
using LibBundle3;
using LibBundle3.Nodes;
using Index = LibBundle3.Index;

namespace PoeDataExtract.Extractors;

/// <summary>
/// Extracts the subset of <c>data/balance/mods.datc64</c> whose
/// <c>Domain == AREA (5)</c> — i.e. every affix the game can roll on
/// a map/area instance. Writes <c>data/map_mod_list.tsv</c>:
///
/// <code>
/// mod_id    affix_name           gen_type    mod_family       level
/// </code>
///
/// PoE2 0.x Mods row layout (verified against dat-schema <c>_Core.gql</c>
/// and the existing <see cref="Mods"/> extractor's anchor offsets):
///
/// <code>
/// @0x00  string-ref       Id              ("MapBlockChance1", …)
/// @0x08  u16              HASH16
/// @0x0A  foreignrow(16)   ModTypeKey      (single — 16 bytes: i64 rid + i64 tableId)
/// @0x1A  i32              Level           — minimum area level the mod can roll on
/// @0x1E  foreignrow(16)   StatsKey1
/// @0x2E  foreignrow(16)   StatsKey2
/// @0x3E  foreignrow(16)   StatsKey3
/// @0x4E  foreignrow(16)   StatsKey4
/// @0x5E  i32 enumrow      Domain          ← the filter column
/// @0x62  string-ref       Name            (matches Mods.OFF_MODS_NAME)
/// @0x6A  i32 enumrow      GenerationType  (matches Mods.OFF_MODS_GEN_TYPE)
/// @0x6E  foreignrow[]     Families        (matches Mods.OFF_MODS_FAMILIES)
/// </code>
///
/// ModDomains enum (dat-schema, 1-indexed):
///   1=ITEM, 2=FLASK, 3=MONSTER, 4=CHEST, 5=AREA, 7=SANCTUM_RELIC,
///   9=CRAFTED, 10=BASE_JEWEL, 11=ATLAS, 12=LEAGUESTONE, 13=ABYSS_JEWEL,
///   14=MAP_DEVICE, 16=DELVE, 17=DELVE_AREA, 18..20=SYNTHESIS_*,
///   21=AFFLICTION_JEWEL, 22=HEIST_AREA, 23=HEIST_NPC, 24=HEIST_TRINKET,
///   25=WATCHSTONE, …
/// AREA (5) is the bucket that backs PoE2 endgame map mods — those are
/// area instances spawned via the Atlas / Map Device, not their own
/// domain.
/// </summary>
internal sealed class MapMods : IExtractor
{
    // Mods columns (offsets match Mods.cs where they overlap)
    private const int OFF_MODS_ID       = 0x00;
    private const int OFF_MODS_LEVEL    = 0x1A;
    private const int OFF_MODS_DOMAIN   = 0x5E;
    private const int OFF_MODS_NAME     = 0x62;
    private const int OFF_MODS_GEN_TYPE = 0x6A;
    private const int OFF_MODS_FAMILIES = 0x6E;

    // ModFamily columns
    private const int OFF_MODFAMILY_ID  = 0x00;

    // We default to AREA (5) but expose the domain via the property so
    // a future caller / CLI flag can override (e.g. ATLAS=11 for map-
    // device-style mods, or FLASK=2 for utility-flask mods).
    public int DomainFilter { get; set; } = 5;

    public void Run(Index index, string outputTsvPath)
    {
        var mods      = OpenDat(index, "data/balance/mods.datc64");
        var modFamily = OpenDat(index, "data/balance/modfamily.datc64");
        Console.Out.WriteLine($"opened: Mods rs={mods.RowSize}#{mods.RowCount}, "
            + $"ModFamily rs={modFamily.RowSize}#{modFamily.RowCount}");

        // ModFamily row → Id string. Same as the Mods extractor.
        var familyIdByRow = new Dictionary<long, string>(modFamily.RowCount);
        for (int i = 0; i < modFamily.RowCount; i++)
        {
            string fid = modFamily.RowString(i, OFF_MODFAMILY_ID);
            if (!string.IsNullOrEmpty(fid)) familyIdByRow[i] = fid;
        }
        Console.Out.WriteLine($"  built family map for {familyIdByRow.Count}/{modFamily.RowCount} ModFamily rows");

        // Diagnostic: print a histogram of Domain values across all mod
        // rows. Helps verify the offset is right AND confirms which
        // bucket the filter is pulling from. The histogram appears in
        // stderr-style stdout, so it doesn't pollute the TSV file.
        var domainHist = new Dictionary<int, int>();
        for (int i = 0; i < mods.RowCount; i++)
        {
            int d = mods.RowI32(i, OFF_MODS_DOMAIN);
            domainHist.TryGetValue(d, out int n);
            domainHist[d] = n + 1;
        }
        Console.Out.WriteLine("  Domain histogram (top 10 by frequency):");
        foreach (var kvp in domainHist.OrderByDescending(kv => kv.Value).Take(10))
            Console.Out.WriteLine($"    Domain={kvp.Key,3}  rows={kvp.Value}");

        var sb = new StringBuilder(capacity: 64 * 1024);
        sb.Append("# map_mod_list.tsv - auto-generated by ggpk-tools/PoeDataExtract\n");
        sb.Append($"# source: data/balance/mods.datc64 filtered by Domain == {DomainFilter} (AREA)\n");
        sb.Append("# columns: mod_id\taffix_name\tgen_type\tmod_family\tlevel\n");
        sb.Append($"# generated: {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}\n");

        int written = 0;
        for (int i = 0; i < mods.RowCount; i++)
        {
            int domain = mods.RowI32(i, OFF_MODS_DOMAIN);
            if (domain != DomainFilter) continue;

            string id    = mods.RowString(i, OFF_MODS_ID);
            string name  = mods.RowString(i, OFF_MODS_NAME);
            int    gen   = mods.RowI32(i, OFF_MODS_GEN_TYPE);
            int    level = mods.RowI32(i, OFF_MODS_LEVEL);
            if (string.IsNullOrEmpty(id)) continue;

            // Defensive — strip tab/newline from strings going into a TSV column.
            name = name.Replace('\t', ' ').Replace('\n', ' ').Replace('\r', ' ');

            // Mods.Families[0].ModFamily → mod-family Id (exclusion group).
            string familyId = "";
            var families = mods.RowArray(i, OFF_MODS_FAMILIES, 16);
            foreach (var famRow in families)
            {
                if (famRow < 0) continue;
                if (!familyIdByRow.TryGetValue(famRow, out var fid)) continue;
                familyId = fid.Replace('\t', ' ').Replace('\n', ' ').Replace('\r', ' ');
                break;
            }

            // GenerationType: 1=Prefix, 2=Suffix, 3=Unique, 4..10=specials.
            // Outside [1..15] → blank (sentinel/unknown).
            string genStr = (gen >= 1 && gen <= 15) ? gen.ToString() : "";

            sb.Append(id).Append('\t').Append(name)
              .Append('\t').Append(genStr).Append('\t').Append(familyId)
              .Append('\t').Append(level).Append('\n');
            written++;
        }

        var dir = Path.GetDirectoryName(outputTsvPath);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        string tmp = outputTsvPath + ".tmp";
        File.WriteAllText(tmp, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        if (File.Exists(outputTsvPath)) File.Delete(outputTsvPath);
        File.Move(tmp, outputTsvPath);
        Console.Out.WriteLine($"wrote {written} map-domain mods to {outputTsvPath}");
    }

    private static DatReader OpenDat(Index index, string path)
    {
        if (!index.TryFindNode(path, out var node) || node is not FileNode file)
            throw new FileNotFoundException(path);
        return new DatReader(file.Record.Read().Span);
    }
}
