using System.Text;
using LibBundle3;
using LibBundle3.Nodes;
using Index = LibBundle3.Index;

namespace PoeDataExtract.Extractors;

/// <summary>
/// Extracts <c>data/mod_name_map.tsv</c> from
/// <c>data/balance/mods.datc64</c>. Consumed by
/// PoE2InventoryReader.LoadModNameMap to look up an affix's display
/// info from its internal mod id.
///
/// PoE2 0.x verified via dat-schema (poe-tool-dev/dat-schema):
///   Mods    rowSize = 677 (odd — DatReader scans byte-by-byte for the marker)
///     @0x00  string-ref     → Id              (e.g. "Strength1")
///     @0x62  string-ref     → Name            ("of the Brute", "Tireless", …)
///     @0x6A  i32 enumrow    → GenerationType  (1=Prefix, 2=Suffix, …)
///     @0x6E  foreignrow[]   → Families        (16-byte slot: count u64 + ptr u64)
///   ModFamily
///     @0x00  string         → Id              (e.g. "Life", "Resistance", …)
///
/// tier_word join: take the first element of Mods.Families
/// (foreignrow → ModFamily) and look up ModFamily.Id. The PoE2
/// "ModFamily" table replaces what PoE1 expressed as a ModType →
/// Words[wordlist=1/3/7] lookup; in PoE2 the family name IS the
/// tier descriptor directly, no Words bounce needed. The old
/// "unnamed `array[]` on ModType row" path is empty across the
/// board in PoE2 0.x (verified by inspection — count=0 for every
/// row), so the schema's still-listed column lives there but isn't
/// populated.
/// </summary>
internal sealed class Mods : IExtractor
{
    // Mods columns
    private const int OFF_MODS_ID         = 0x00;
    private const int OFF_MODS_NAME       = 0x62;
    private const int OFF_MODS_GEN_TYPE   = 0x6A;
    private const int OFF_MODS_FAMILIES   = 0x6E;  // 110 — foreignrow[] count+ptr

    // ModFamily columns
    private const int OFF_MODFAMILY_ID    = 0x00;

    public void Run(Index index, string outputTsvPath)
    {
        var mods      = OpenDat(index, "data/balance/mods.datc64");
        var modFamily = OpenDat(index, "data/balance/modfamily.datc64");
        Console.Out.WriteLine($"opened: Mods rs={mods.RowSize}#{mods.RowCount}, "
            + $"ModFamily rs={modFamily.RowSize}#{modFamily.RowCount}");

        // 1) ModFamily row → Id string. In PoE2 the family name IS
        //    the tier descriptor ("Life", "Damage", "Resistance", …)
        //    — no Words bounce needed (that was the PoE1 path).
        var familyIdByRow = new Dictionary<long, string>(modFamily.RowCount);
        for (int i = 0; i < modFamily.RowCount; i++)
        {
            string fid = modFamily.RowString(i, OFF_MODFAMILY_ID);
            if (!string.IsNullOrEmpty(fid)) familyIdByRow[i] = fid;
        }
        Console.Out.WriteLine($"  built family map for {familyIdByRow.Count}/{modFamily.RowCount} ModFamily rows");

        // 2) Walk Mods. Mods.Families is foreignrow[] (16 bytes per
        //    element — first u64 = ModFamily row, second u64 = table
        //    id, ignored). Take the first valid element as the
        //    tier_word for this mod.
        var sb = new StringBuilder(capacity: mods.RowCount * 48);
        sb.Append("# mod_name_map.tsv - auto-generated by ggpk-tools/PoeDataExtract\n");
        sb.Append("# source: data/balance/mods.datc64 + ModFamily (2-way join via Mods.Families[0])\n");
        sb.Append("# columns: mod_id\taffix_name\tgen_type\ttier_word\n");
        sb.Append($"# generated: {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}\n");

        int written = 0, withTier = 0, withName = 0;
        for (int i = 0; i < mods.RowCount; i++)
        {
            string id   = mods.RowString(i, OFF_MODS_ID);
            string name = mods.RowString(i, OFF_MODS_NAME);
            int    gen  = mods.RowI32(i, OFF_MODS_GEN_TYPE);
            if (string.IsNullOrEmpty(id)) continue;

            // Defensive — strip tab/newline from strings going into a TSV column.
            name = name.Replace('\t', ' ').Replace('\n', ' ').Replace('\r', ' ');

            // Mods.Families[0].ModFamily → tier word.
            string tierWord = "";
            var families = mods.RowArray(i, OFF_MODS_FAMILIES, 16);
            foreach (var famRow in families)
            {
                if (famRow < 0) continue;
                if (!familyIdByRow.TryGetValue(famRow, out var fid)) continue;
                tierWord = fid.Replace('\t', ' ').Replace('\n', ' ').Replace('\r', ' ');
                break;
            }

            // GenerationType enumrow values from PoE schemas:
            //   1=Prefix, 2=Suffix, 3=Unique, 4..10=specials.
            // Outside [1..15] = sentinel/unknown — emit blank instead
            // of a confusing negative number.
            string genStr = (gen >= 1 && gen <= 15) ? gen.ToString() : "";

            sb.Append(id).Append('\t').Append(name)
              .Append('\t').Append(genStr).Append('\t').Append(tierWord).Append('\n');
            written++;
            if (!string.IsNullOrEmpty(name))     withName++;
            if (!string.IsNullOrEmpty(tierWord)) withTier++;
        }

        var dir = Path.GetDirectoryName(outputTsvPath);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        string tmp = outputTsvPath + ".tmp";
        File.WriteAllText(tmp, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        if (File.Exists(outputTsvPath)) File.Delete(outputTsvPath);
        File.Move(tmp, outputTsvPath);
        Console.Out.WriteLine($"wrote {written} rows to {outputTsvPath} "
            + $"({withName} with name, {withTier} with tier word)");
    }

    private static DatReader OpenDat(Index index, string path)
    {
        if (!index.TryFindNode(path, out var node) || node is not FileNode file)
            throw new FileNotFoundException(path);
        return new DatReader(file.Record.Read().Span);
    }
}
