using System.Text;
using LibBundle3;
using LibBundle3.Nodes;
using Index = LibBundle3.Index;

namespace PoeDataExtract.Extractors;

/// <summary>
/// Extracts <c>data/mod_name_map.tsv</c> from
/// <c>data/balance/mods.datc64</c>. Consumed by
/// PoE2InventoryReader.LoadModNameMap to look up an affix's display
/// info from its internal mod id.
///
/// PoE2 0.x verified via dat-schema (poe-tool-dev/dat-schema):
///   rowSize = 677 (odd — DatReader scans byte-by-byte to find the marker)
///   @0x00  string-ref → Id              (e.g. "Strength1")
///   @0x62  string-ref → Name             ("of the Brute", "Tireless", …)
///   @0x6A  i32 enumrow → GenerationType  (1=Prefix, 2=Suffix, 3=Unique, …)
///
/// Note the Name column at offset 98 (0x62) is NOT 8-byte-aligned —
/// PoE2's row layout packs string refs at whatever offset the schema
/// dictates. Inspection alone never reveals these because the
/// candidate-scan steps in 8s.
///
/// tier_word column intentionally left blank for now — it requires
/// joining Mods.Families → ModFamily.Id → Words.text, which needs the
/// u64 foreign-key support in DatReader (TODO, same as UniqueNames).
/// </summary>
internal sealed class Mods : IExtractor
{
    private const int OffsetId      = 0x00;
    private const int OffsetName    = 0x62;  // 98, per dat-schema
    private const int OffsetGenType = 0x6A;  // 106, enumrow → int32

    public void Run(Index index, string outputTsvPath)
    {
        string[] candidates = { "data/balance/mods.datc64", "Data/Mods.dat64" };
        FileNode? fileNode = null;
        foreach (var c in candidates)
        {
            if (index.TryFindNode(c, out var node) && node is FileNode fn) { fileNode = fn; break; }
        }
        if (fileNode is null)
            throw new FileNotFoundException(string.Join(" / ", candidates));

        var dat = new DatReader(fileNode.Record.Read().Span);
        Console.Out.WriteLine($"opened {candidates[0]}: rowCount={dat.RowCount} rowSize={dat.RowSize}");

        var sb = new StringBuilder(capacity: dat.RowCount * 32);
        sb.Append("# mod_name_map.tsv - auto-generated by ggpk-tools/PoeDataExtract\n");
        sb.Append("# source: data/balance/mods.datc64\n");
        sb.Append("# columns: mod_id\taffix_name\tgen_type\ttier_word\n");
        sb.Append("# NOTE: tier_word is still empty — needs Mods.Families →\n");
        sb.Append("# ModFamily → Words join (TODO: u64 FK support in DatReader).\n");
        sb.Append($"# generated: {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}\n");
        int written = 0;
        for (int i = 0; i < dat.RowCount; i++)
        {
            string id   = dat.RowString(i, OffsetId);
            string name = dat.RowString(i, OffsetName);
            int    gen  = dat.RowI32(i, OffsetGenType);
            if (string.IsNullOrEmpty(id)) continue;
            // Defensive — tabs/newlines in affix names would break the column count.
            name = name.Replace('\t', ' ').Replace('\n', ' ').Replace('\r', ' ');
            // GenerationType enumrow values from PoE schemas:
            //   1 = Prefix, 2 = Suffix, 3 = Unique, 4..10 = various
            //     specials (Nemesis, Corrupted, Bloodlines, Tormented,
            //     Tempest, Talisman, Enchantment, …).
            // Anything outside [1..15] is either the FE-sentinel
            // (read as -16843010) or a row holding no proper enum value
            // (corrupted / implicit / Synthesis-style mods that store
            // the generation hint elsewhere). Surface those as blank
            // rather than confusing the consumer with bogus negative
            // numbers.
            string genStr = (gen >= 1 && gen <= 15) ? gen.ToString() : "";
            sb.Append(id).Append('\t').Append(name)
              .Append('\t').Append(genStr).Append("\t\n");
            written++;
        }

        var dir = Path.GetDirectoryName(outputTsvPath);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        string tmp = outputTsvPath + ".tmp";
        File.WriteAllText(tmp, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        if (File.Exists(outputTsvPath)) File.Delete(outputTsvPath);
        File.Move(tmp, outputTsvPath);
        Console.Out.WriteLine($"wrote {written} rows to {outputTsvPath} (modId-only — see header for limitation)");
    }
}
