using System.Text;
using LibBundle3;
using LibBundle3.Nodes;
using Index = LibBundle3.Index;

namespace PoeDataExtract.Extractors;

/// <summary>
/// Extracts <c>data/stat_name_map.tsv</c> from
/// <c>data/balance/stats.datc64</c>. Used at runtime by
/// TreeView_StatsFormatting / WebViewBridge to validate that a stat
/// id seen in memory is one of the game's known stats.
///
/// PoE2 0.x verified (May 2026):
///   rowSize = 106, auto-detected via the BB marker scan
///   @0x00  int64 string-ref → stat id (e.g. "level", "item_drop_slots")
///
/// Stats are identified by their string id; there's no separate
/// "display name" column — descriptions live in StatDescriptions/*.csd
/// which is the stat_desc_map.tsv pipeline (still Python for now).
///
/// Output TSV format (row index → stat id, matching the legacy
/// extract_stats_dat_csv.py output the AHK side expects):
///   0   level
///   1   item_drop_slots
///   2   main_hand_weapon_type
///   …
/// The row-index column is what GetCachedStatNameMap uses as the key
/// when resolving a stat ref it pulls from memory (the game stores
/// stats by row index, not by name).
/// </summary>
internal sealed class StatNames : IExtractor
{
    private const int OffsetId = 0x00;

    public void Run(Index index, string outputTsvPath)
    {
        string[] candidates = { "data/balance/stats.datc64", "Data/Stats.dat64" };
        FileNode? fileNode = null;
        foreach (var c in candidates)
        {
            if (index.TryFindNode(c, out var node) && node is FileNode fn) { fileNode = fn; break; }
        }
        if (fileNode is null)
            throw new FileNotFoundException(string.Join(" / ", candidates));

        var dat = new DatReader(fileNode.Record.Read().Span);
        Console.Out.WriteLine($"opened {candidates[0]}: rowCount={dat.RowCount} rowSize={dat.RowSize}");

        var sb = new StringBuilder(capacity: dat.RowCount * 32);
        // Comment header — matches the legacy Python format so existing
        // consumers don't need to learn about new metadata.
        sb.Append("# stat_name_map.tsv - auto-generated by ggpk-tools/PoeDataExtract\n");
        sb.Append("# source: data/balance/stats.datc64\n");
        sb.Append($"# generated: {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}\n");
        int written = 0;
        for (int i = 0; i < dat.RowCount; i++)
        {
            string id = dat.RowString(i, OffsetId);
            if (string.IsNullOrEmpty(id)) continue;
            // Row index is the lookup key — the game stores stat refs
            // by index, not by string.
            sb.Append(i).Append('\t').Append(id).Append('\n');
            written++;
        }

        var dir = Path.GetDirectoryName(outputTsvPath);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        string tmp = outputTsvPath + ".tmp";
        File.WriteAllText(tmp, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        if (File.Exists(outputTsvPath)) File.Delete(outputTsvPath);
        File.Move(tmp, outputTsvPath);
        Console.Out.WriteLine($"wrote {written} rows to {outputTsvPath}");
    }
}
