"""
Extract monster display names from a pre-dumped MonsterVarieties CSV.

Requires: poe_data_tools (Rust) to have already exported the CSV via:
  poe_data_tools --patch 2 dump-tables "Data/Balance/MonsterVarieties.datc64"

This replaces the old extract_monster_names.py which did raw binary
datc64 parsing, OOZ decompression, schema downloading, etc.

Output:
  monster_name_map.tsv   (same format as the original script)

Usage:
  python extract_monster_names_csv.py [csv_dir] [output_tsv]

  csv_dir  = folder containing MonsterVarieties.csv (default: data/raw_csv)
  output   = TSV path (default: data/monster_name_map.tsv)
"""

import csv
import os
import sys
import time


def normalize_key(s):
    return (s or "").strip().replace("\\", "/").lower()


def add_mapping(mapping, key, value):
    k = normalize_key(key)
    v = (value or "").strip()
    if not k or not v:
        return
    if k not in mapping:
        mapping[k] = v


def build_monster_name_map(csv_path):
    """Read MonsterVarieties.csv and build key→displayName mapping."""
    mapping = {}

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        # Verify expected columns exist
        if "Id" not in reader.fieldnames or "Name" not in reader.fieldnames:
            raise ValueError(
                f"CSV missing required columns. "
                f"Found: {reader.fieldnames[:10]}... "
                f"Expected 'Id' and 'Name'"
            )

        for row in reader:
            monster_id = row.get("Id", "")
            monster_name = row.get("Name", "")

            if not monster_id or not monster_name:
                continue

            # Full path key (e.g. "metadata/monsters/...")
            add_mapping(mapping, monster_id, monster_name)

            # Short basename key (e.g. "abyssalcrystalwaller")
            short = monster_id.rsplit("/", 1)[-1]
            add_mapping(mapping, short, monster_name)
            # Trailing underscore variant
            add_mapping(mapping, short.rstrip("_"), monster_name)

    return mapping


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(os.path.dirname(script_dir), "data")

    csv_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(data_dir, "raw_csv", "data", "balance")
    output_tsv = (
        sys.argv[2]
        if len(sys.argv) > 2
        else os.path.join(data_dir, "monster_name_map.tsv")
    )

    csv_path = os.path.join(csv_dir, "MonsterVarieties.csv")
    if not os.path.isfile(csv_path):
        print(f"ERROR: CSV not found: {csv_path}")
        print()
        print("Generate it first with poe_data_tools:")
        print(
            '  poe_data_tools --patch 2 dump-tables '
            '"Data/Balance/MonsterVarieties.datc64" '
            f'--output "{csv_dir}"'
        )
        sys.exit(1)

    mapping = build_monster_name_map(csv_path)

    if not mapping:
        print("ERROR: no monster name mappings extracted")
        sys.exit(1)

    os.makedirs(os.path.dirname(output_tsv), exist_ok=True)
    with open(output_tsv, "w", encoding="utf-8", newline="\n") as f:
        f.write("# monster_name_map.tsv - auto-generated by extract_monster_names_csv.py\n")
        f.write(f"# source: {csv_path}\n")
        f.write(f"# generated: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n")
        for k in sorted(mapping.keys()):
            f.write(f"{k}\t{mapping[k]}\n")

    print(f"Extracted {len(mapping):,} mappings -> {output_tsv}")


if __name__ == "__main__":
    main()
