"""
Extract mod names from a pre-dumped Mods CSV.

Requires: poe_data_tools to have already exported the CSV via:
  poe_data_tools --patch 2 dump-tables "Data/Balance/Mods.datc64"

Output:
  mod_name_map.tsv  (mod_id TAB name TAB generation_type)
  Same format as the original extract_mods_dat.py

Usage:
  python extract_mods_dat_csv.py [csv_dir] [output_tsv]
"""

import csv
import os
import sys
import time


def build_mod_name_map(csv_path):
    """Read Mods.csv and return list of (mod_id, name, gen_type) tuples."""
    entries = []

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        required = {"Id", "Name", "GenerationType"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(
                f"CSV missing columns: {missing}. Found: {reader.fieldnames[:15]}"
            )

        for row in reader:
            mod_id = row.get("Id", "").strip()
            if not mod_id:
                continue

            name = row.get("Name", "").strip()
            try:
                gen_type = int(row.get("GenerationType", "0"))
            except ValueError:
                gen_type = 0

            entries.append((mod_id, name, gen_type))

    return entries


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(os.path.dirname(script_dir), "data")

    csv_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(data_dir, "raw_csv", "data", "balance")
    output_tsv = (
        sys.argv[2]
        if len(sys.argv) > 2
        else os.path.join(data_dir, "mod_name_map.tsv")
    )

    csv_path = os.path.join(csv_dir, "Mods.csv")
    if not os.path.isfile(csv_path):
        print(f"ERROR: CSV not found: {csv_path}")
        print()
        print("Generate it first with poe_data_tools:")
        print(
            '  poe_data_tools --patch 2 dump-tables '
            '"Data/Balance/Mods.datc64" '
            f'--output "{csv_dir}"'
        )
        sys.exit(1)

    entries = build_mod_name_map(csv_path)

    if not entries:
        print("ERROR: No mod entries found in CSV")
        sys.exit(1)

    os.makedirs(os.path.dirname(output_tsv), exist_ok=True)
    with open(output_tsv, "w", encoding="utf-8", newline="\n") as f:
        f.write("# mod_name_map.tsv - auto-generated by extract_mods_dat_csv.py\n")
        f.write(f"# source: {csv_path}\n")
        f.write(f"# generated: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n")
        f.write("# columns: mod_id\tname\tgen_type(1=Prefix,2=Suffix)\n")
        for mod_id, name, gen_type in entries:
            f.write(f"{mod_id}\t{name}\t{gen_type}\n")

    with_name = sum(1 for _, n, _ in entries if n)
    print(f"Extracted {len(entries):,} mods ({with_name:,} with names) -> {output_tsv}")


if __name__ == "__main__":
    main()
