"""
Extract stat names from a pre-dumped Stats CSV.

Requires: poe_data_tools to have already exported the CSV via:
  poe_data_tools --patch 2 dump-tables "Data/Balance/Stats.datc64"

Output:
  stat_name_map.tsv  (row_index TAB stat_id)
  Same format as the original extract_stats_dat.py

Usage:
  python extract_stats_dat_csv.py [csv_dir] [output_tsv]
"""

import csv
import os
import sys
import time


def build_stat_name_map(csv_path):
    """Read Stats.csv and return list of (row_index, stat_id) tuples."""
    entries = []

    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        if "Id" not in reader.fieldnames:
            raise ValueError(
                f"CSV missing 'Id' column. Found: {reader.fieldnames[:10]}"
            )

        for row_idx, row in enumerate(reader):
            stat_id = row.get("Id", "").strip()
            if stat_id:
                entries.append((row_idx, stat_id))

    return entries


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(os.path.dirname(script_dir), "data")

    csv_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(data_dir, "raw_csv", "data", "balance")
    output_tsv = (
        sys.argv[2]
        if len(sys.argv) > 2
        else os.path.join(data_dir, "stat_name_map.tsv")
    )

    csv_path = os.path.join(csv_dir, "Stats.csv")
    if not os.path.isfile(csv_path):
        print(f"ERROR: CSV not found: {csv_path}")
        print()
        print("Generate it first with poe_data_tools:")
        print(
            '  poe_data_tools --patch 2 dump-tables '
            '"Data/Balance/Stats.datc64" '
            f'--output "{csv_dir}"'
        )
        sys.exit(1)

    entries = build_stat_name_map(csv_path)

    if not entries:
        print("ERROR: No stat entries found in CSV")
        sys.exit(1)

    os.makedirs(os.path.dirname(output_tsv), exist_ok=True)
    with open(output_tsv, "w", encoding="utf-8", newline="\n") as f:
        f.write("# stat_name_map.tsv - auto-generated by extract_stats_dat_csv.py\n")
        f.write(f"# source: {csv_path}\n")
        f.write(f"# generated: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n")
        f.write("# key=row_index (0-based), matches PoE2 character stat pair keys in memory\n")
        for row_idx, stat_id in entries:
            f.write(f"{row_idx}\t{stat_id}\n")

    print(f"Extracted {len(entries):,} stats -> {output_tsv}")


if __name__ == "__main__":
    main()
